### ISSUE TITLE
Signature spoofing support

### ISSUE THREAD

**Issue by bam80** [CarbonROM/android_frameworks_base#10]
Hi,
could you please apply following patch for the Signature spoofing support?
https://github.com/microg/android_packages_apps_GmsCore/pull/365
Thanks in advice

**Comment by Myself5** [comment]
Hi,

Except for the fake location path (which is currently in review) we already have support for microG apps.

**Comment by bam80** [comment]
Nice to hear!
However, on my understanding microG Services can't be supported without the Signature spoofing. Am I wrong?
If not, does it mean that CarbonROM already has Signature spoofing?
@Myself5, could you explain, please?

**Comment by Myself5** [comment]
Carbon had support for signature spoofing for quite a while now.
The fake location patch has been merged some days ago, which means you can expect that to be included in todays Weeklies.

**Comment by bam80** [comment]
Thank you Christian for a quick answer!
I'm very happy that at least someone accepted these patches!
It's a big reason to try Carbon now, for sure :)

**Comment by takiainen** [comment]
It doesn't seem to work. Microg selfcheck says spoofing is not supported. Also another spoofing checker app from Fdroid says "signature spoofing isn't supported". What to do?

**Comment by bam80** [comment]
@takiainen you should enable Signature spoofing permissions for Microg app. Don't use checker app from Fdroid on this ROM - Signature spoofing is only supported for Microg, so only Microg selfcheck useful.

**Comment by doctorsangria** [comment]
@bam80 could you let us know how to do this? I'm having this same issue and I can't find signature spoofing settings anywhere, nor do I get any popup or anything like that. Don't know where to look

**Comment by bam80** [comment]
@ale-reyes Sure. On Oreo, you could see "Spoof package signature" permissions in 'Settings -> Apps & Notifications -> App permissions' screen (near the bottom). But you don't have to set them manually - MicroG capable to request all needed permissions during setup Self-Check stage.

**Comment by doctorsangria** [comment]
Hmm. I might have done something wrong installing the ROM then, because I'm not seeing that at all. I'll wipe and start from scratch I suppose.
________________________________

**Comment by bam80** [comment]
@ale-reyes did you try to request Signature spoofing permissions from within MicroG app itself?

**Comment by doctorsangria** [comment]
I did, and it wasn't helping. I just reflashed everything and it's fine (ish). Now I'm having separate issues BUT if I can't figure it out I'll open a separate thread for it. Thanks for the quick responses.
________________________________
