### ISSUE TITLE
 EasterEgg in CarbonPie

### ISSUE THREAD

**Issue by Dargons10** [CarbonROM/android_frameworks_base#13]
Hi. 
Im trying to compile pie for Mi Pad (mocha), but i get the next problem during the build:
[ 62% 22074/35507] //frameworks/base/packages/EasterEgg:EasterEgg aapt2 link
FAILED: /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/package-res.apk /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/proguard.options /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/R.jar /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/R.txt /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/extra_packages 
/media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/host/linux-x86/bin/aapt2 link -o /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/package-res.apk --no-static-lib-packages --manifest frameworks/base/packages/EasterEgg/AndroidManifest.xml  -I prebuilts/sdk/current/android.jar --min-sdk-version 28 --target-sdk-version 28 --version-code 28 --version-name  9 --product tablet tablet -c en_US,en_US,af_ZA,am_ET,ar_EG,ar_XB,as_IN,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,en_XC,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,or_IN,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,xlarge,large --java /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/aapt2/R --proguard /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/proguard.options --output-text-symbols /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/R.txt @/media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/aapt2/res.list && /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/host/linux-x86/bin/soong_zip -write_if_changed -jar -o /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/R.jar -C /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/aapt2/R -D /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/aapt2/R &&/media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/host/linux-x86/bin/extract_jar_packages -i /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/gen/R.jar -o /media/dargons10/df110470-b0ff-4d8d-b174-2c8b3f6777e1/carbonpie/out/soong/.intermediates/frameworks/base/packages/EasterEgg/EasterEgg/android_common/extra_packages --prefix '--extra-packages '
tablet: error: failed to open file: No such file or directory.

Id like if is possible that this error will be fix it please. Thanks a lot

**Comment by Myself5** [comment]
This isn't an issue with the EasterEgg app, but appears to be with your device trees. ` --product tablet tablet` leads to the assumption that you're defining PRODUCT_CHARACTERISTICS as "tablet tablet" somewhere.

Be aware that it's already defined once in vendor/carbon/common_tablet.mk, so technically you wouldn't need to set it in your device trees at all.

**Comment by Dargons10** [comment]
i was driving me crazy to know why i get this errors. Yes, in my device, i have defined like tablet.
Ill deleted and try again.
Thanks a lot.

**Comment by Dargons10** [comment]
> This isn't an issue with the EasterEgg app, but appears to be with your device trees. ` --product tablet tablet` leads to the assumption that you're defining PRODUCT_CHARACTERISTICS as "tablet tablet" somewhere.
> 
> Be aware that it's already defined once in vendor/carbon/common_tablet.mk, so technically you wouldn't need to set it in your device trees at a all.

**Comment by Dargons10** [comment]
Thanks a lot, but i get other problem, and that is a sources problem. 

Now, i get problemn with frameworks-javastream-protos
