### ISSUE TITLE
Ask : Where to Start ?

### ISSUE THREAD

**Issue by ejabu** [CarbonROM/android_frameworks_base#9]
Hi Guys, 

I am completely new to Android Mod - Development

can someone Help me where to start by using Carbon ROM ?

My final Goal is I have an Android OS, which has no installed BROWSER and Google Play Store.

I need them, so my child can utilize the smart phone without being able to be contaminated with internet negative stuffs.

Thanks ~ !

**Comment by Myself5** [comment]
As we don't ship Google Services by default, all you'd need to do is to disable Quarks. For that you can just remove the /system/app/Browser folder using TWRP.

**Comment by ejabu** [comment]
Noted.

But I still have lot of confusion.

would you like to help me to list all the basic required packages/repo to look up for?

best regards
